sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t bhargav1993/docker-cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true bhargav1993/docker-cicd npm run test